services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code

volumes:
  static_volume:
  media_volume: